# Generated by Django 5.2.5 on 2025-12-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decks', '0002_remove_flashcard_author_remove_flashcard_deck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chinesedeck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chinesedeck',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='japanesedeck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='japanesedeck',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='koreandeck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='koreandeck',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
    ]
