# Generated by Django 5.2.5 on 2025-12-31 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Decks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('hanzi', models.CharField(max_length=40, null=True)),
                ('pinyin', models.CharField(max_length=120, null=True)),
                ('language', models.CharField(default='ZH', max_length=2)),
                ('hsk_level', models.CharField(choices=[('HSK1', 'HSK 1'), ('HSK2', 'HSK 2'), ('HSK3', 'HSK 3'), ('HSK4', 'HSK 4'), ('HSK5', 'HSK 5'), ('HSK6', 'HSK 6')], db_index=True, default='HSK1', max_length=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinese_deck', to='Decks.chinesedeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('word', models.CharField(db_index=True, max_length=200, null=True)),
                ('language', models.CharField(default='EN', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_deck', to='Decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2)),
                ('word', models.CharField(db_index=True, max_length=200, null=True)),
                ('language', models.CharField(choices=[('ES', 'Spanish'), ('FR', 'French'), ('IT', 'Italian'), ('DE', 'Deutsch'), ('PT', 'Portuguese'), ('RU', 'Russian')], db_index=True, default='ES', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck', to='Decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HindiFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('devanagari', models.CharField(max_length=50)),
                ('transliteration', models.CharField(max_length=100)),
                ('language', models.CharField(default='HI', max_length=2)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='A1', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hindi_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hindi_deck', to='Decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JapaneseFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('kanji', models.CharField(blank=True, max_length=50, null=True)),
                ('kana', models.CharField(max_length=50)),
                ('romaji', models.CharField(max_length=100)),
                ('language', models.CharField(default='JP', max_length=2)),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], db_index=True, default='N5', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='japanese_deck', to='Decks.japanesedeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KoreanFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('hangul', models.CharField(max_length=50)),
                ('romaji', models.CharField(max_length=100)),
                ('language', models.CharField(default='KO', max_length=2)),
                ('topik_level', models.CharField(choices=[('TOPIK-I-1', 'TOPIK-I-1'), ('TOPIK-I-2', 'TOPIK-I-2'), ('TOPIK-II-3', 'TOPIK-II-3'), ('TOPIK-II-4', 'TOPIK-II-4'), ('TOPIK-II-5', 'TOPIK-II-5'), ('TOPIK-II-6', 'TOPIK-II-6')], db_index=True, default='TOPIK-I-1', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korean_deck', to='Decks.koreandeck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RussianFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('cyrillic', models.CharField(max_length=50)),
                ('transliteration', models.CharField(max_length=100)),
                ('language', models.CharField(default='RU', max_length=2)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='A1', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='russian_deck', to='Decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
