# Generated by Django 5.2.5 on 2025-08-17 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decks', '0002_remove_flashcard_author_remove_flashcard_deck_and_more'),
        ('Flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='language',
            field=models.CharField(choices=[('ES', 'Spanish'), ('FR', 'French'), ('IT', 'Italian'), ('DE', 'Deutsch'), ('PT', 'Portuguese'), ('RU', 'Russian')], db_index=True, default='ES', max_length=2),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='word',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='EnglishFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(db_index=True, max_length=200, null=True)),
                ('language', models.CharField(default='EN', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_deck', to='Decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
