# Generated by Django 5.2.5 on 2025-08-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0002_flashcard_language_alter_flashcard_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishflashcard',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], default='A1', max_length=2),
        ),
    ]
