# Generated by Django 5.2.5 on 2025-08-17 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decks', '0002_remove_flashcard_author_remove_flashcard_deck_and_more'),
        ('Flashcards', '0003_englishflashcard_cefr_level_flashcard_cefr_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chineseflashcard',
            name='hsk_level',
            field=models.CharField(choices=[('HSK1', 'HSK 1'), ('HSK2', 'HSK 2'), ('HSK3', 'HSK 3'), ('HSK4', 'HSK 4'), ('HSK5', 'HSK 5'), ('HSK6', 'HSK 6')], db_index=True, default='HSK1', max_length=4),
        ),
        migrations.AddField(
            model_name='chineseflashcard',
            name='language',
            field=models.CharField(default='ZH', max_length=2),
        ),
        migrations.AddField(
            model_name='japaneseflashcard',
            name='jlpt_level',
            field=models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], db_index=True, default='N5', max_length=2),
        ),
        migrations.AddField(
            model_name='japaneseflashcard',
            name='language',
            field=models.CharField(default='JP', max_length=2),
        ),
        migrations.AddField(
            model_name='koreanflashcard',
            name='language',
            field=models.CharField(default='KO', max_length=2),
        ),
        migrations.AddField(
            model_name='koreanflashcard',
            name='topik_level',
            field=models.CharField(choices=[('TOPIK-I-1', 'TOPIK-I-1'), ('TOPIK-I-2', 'TOPIK-I-2'), ('TOPIK-II-3', 'TOPIK-II-3'), ('TOPIK-II-4', 'TOPIK-II-4'), ('TOPIK-II-5', 'TOPIK-II-5'), ('TOPIK-II-6', 'TOPIK-II-6')], db_index=True, default='TOPIK-I-1', max_length=10),
        ),
        migrations.AddField(
            model_name='russianflashcard',
            name='cefr_level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='A1', max_length=2),
        ),
        migrations.AddField(
            model_name='russianflashcard',
            name='language',
            field=models.CharField(default='RU', max_length=2),
        ),
        migrations.CreateModel(
            name='HindiFlashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(max_length=200)),
                ('example_phrase', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('devanagari', models.CharField(max_length=50)),
                ('transliteration', models.CharField(max_length=100)),
                ('language', models.CharField(default='HI', max_length=2)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], db_index=True, default='A1', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hindi_flashcard_author', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hindi_deck', to='Decks.deck')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
