# Generated by Django 5.2.5 on 2025-12-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0004_chineseflashcard_hsk_level_chineseflashcard_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chineseflashcard',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='englishflashcard',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='hindiflashcard',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='japaneseflashcard',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='koreanflashcard',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='russianflashcard',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chineseflashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='englishflashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hindiflashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='japaneseflashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='koreanflashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='russianflashcard',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-06-22:43:50'),
            preserve_default=False,
        ),
    ]
