# Generated by Django 5.2.5 on 2025-12-13 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hi, recent updates here', max_length=50)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(choices=[('ACCOUNT', 'Account'), ('SOCIAL', 'Social'), ('LEARNING', 'Learning'), ('LESSON', 'Lesson'), ('ACHIEVEMENT', 'Achievement'), ('CHALLENGE', 'Challenge'), ('FRIEND_REQUEST', 'Friend Request'), ('MESSAGE', 'Messages'), ('SYSTEM', 'System'), ('PROMOTIONAL', 'Promotion'), ('REMINDER', 'Reminder'), ('LEVEL_UP', 'Level Up'), ('STREAK', 'Streak'), ('NEW_CONTENT', 'New Content'), ('CREATED_DECK', 'Created Deck'), ('OBTAINED_DECK', 'Obtained Deck')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatary', 'is_read'], name='Notificatio_destina_f7fc11_idx'), models.Index(fields=['created_at'], name='Notificatio_created_e9230d_idx'), models.Index(fields=['category'], name='Notificatio_categor_f8d4d9_idx')],
            },
        ),
    ]
