# Generated by Django 4.2.11 on 2025-07-26 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Hi, recent updates here', max_length=50)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(choices=[('ACCOUNT', 'Account'), ('SOCIAL', 'Social'), ('LEARNING', 'Learning'), ('LESSON', 'Lesson Updates'), ('PRACTICE', 'Practice Reminders'), ('ACHIEVEMENT', 'Achievements'), ('CHALLENGE', 'Challenges'), ('FRIEND_REQUEST', 'Friend Requests'), ('MESSAGE', 'Messages'), ('SYSTEM', 'System Alerts'), ('PROMOTIONAL', 'Promotional'), ('REMINDER', 'Study Reminders'), ('LEVEL_UP', 'Level Up'), ('STREAK', 'Streak Notifications'), ('NEW_CONTENT', 'New Content Available')], default='SYSTEM', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinatary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinatary', 'is_read'], name='Notificatio_destina_f7fc11_idx'), models.Index(fields=['created_at'], name='Notificatio_created_e9230d_idx'), models.Index(fields=['category'], name='Notificatio_categor_f8d4d9_idx')],
            },
        ),
    ]
