# Generated by Django 4.2.11 on 2025-07-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('SOCIAL', 'Social'), ('LEARNING', 'Learning'), ('LESSON', 'Lesson Updates'), ('PRACTICE', 'Practice Reminders'), ('ACHIEVEMENT', 'Achievements'), ('CHALLENGE', 'Challenges'), ('FRIEND_REQUEST', 'Friend Requests'), ('MESSAGE', 'Messages'), ('SYSTEM', 'System Alerts'), ('PROMOTIONAL', 'Promotional'), ('REMINDER', 'Study Reminders'), ('LEVEL_UP', 'Level Up'), ('STREAK', 'Streak Notifications'), ('NEW_CONTENT', 'New Content Available'), ('NEW_LIBRARY_DECK', 'New Library Deck To Study')], default='SYSTEM', max_length=20),
        ),
    ]
