# Generated by Django 4.2.11 on 2025-07-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0003_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('ACCOUNT', 'Account'), ('SOCIAL', 'Social'), ('LEARNING', 'Learning'), ('LESSON', 'Lesson'), ('ACHIEVEMENT', 'Achievement'), ('CHALLENGE', 'Challenge'), ('FRIEND_REQUEST', 'Friend Request'), ('MESSAGE', 'Messages'), ('SYSTEM', 'System'), ('PROMOTIONAL', 'Promotion'), ('REMINDER', 'Reminder'), ('LEVEL_UP', 'Level Up'), ('STREAK', 'Streak'), ('NEW_CONTENT', 'New Content'), ('CREATED_DECK', 'Created Deck'), ('OBTAINED_DECK', 'Obtained Deck')], default='SYSTEM', max_length=20),
        ),
    ]
