# Generated by Django 5.2.5 on 2025-12-13 14:14

import Hub.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(blank=True, db_index=True, default='EN', max_length=3)),
                ('title', models.CharField(max_length=150)),
                ('opinion', models.TextField(blank=True, null=True)),
                ('speech', models.FileField(blank=True, null=True, upload_to='post_audios/', validators=[Hub.validators.validate_audio_file])),
                ('image', models.FileField(blank=True, null=True, upload_to='post_images/', validators=[Hub.validators.validate_image_file])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('speech', models.FileField(blank=True, null=True, upload_to='comment_audios/', validators=[Hub.validators.validate_audio_file])),
                ('image', models.FileField(blank=True, null=True, upload_to='comment_images/', validators=[Hub.validators.validate_image_file])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Hub.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
