# Generated by Django 5.2.5 on 2025-12-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='post',
            new_name='post_id',
        ),
    ]
