# Generated by Django 5.2.5 on 2025-10-20 17:17

import Hub.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_images/', validators=[Hub.validators.validate_image_file]),
        ),
    ]
