# Generated by Django 5.2.5 on 2025-12-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hub', '0003_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, db_index=True, default='EN', max_length=3),
        ),
    ]
